# specific path build
trigger:
  batch: true
  branches:
    include:
    - master
  paths:
    exclude:
    - '*.md'

jobs:
- job: Complie
  pool:
    name: 'Ubuntu1804'

  steps:
    - bash: |
        sudo apt -y update
        sudo apt -y upgrade
        sudo apt -y install asciidoc gettext libncurses5-dev libz-dev lib32gcc1 libc6-dev-i386 flex uglifyjs gcc-multilib msmtp texinfo xmlto qemu-utils upx libelf-dev autopoint device-tree-compiler
      displayName: 'Install dependencies'
    - bash: |
        ./ci/build.sh
      displayName: 'Build'
    - bash: |
        cp -r ./lede/bin/targets/ $(Build.ArtifactStagingDirectory)/
      displayName: 'Copy files to artifacts directory'
    - task: PublishBuildArtifacts@1
      inputs:
        PathtoPublish: '$(Build.ArtifactStagingDirectory)'
        ArtifactName: lede
        publishLocation: Container
      condition: succeededOrFailed()
      displayName: 'Publish artifacts'

  timeoutInMinutes: 300
