# specific path build
trigger:
  batch: true
  branches:
    include:
    - master
  paths:
    exclude:
    - '*.md'
    - '.github/*'

jobs:
- job: Complie
  pool:
    name: 'Ubuntu1804'

  steps:
    - bash: |
        sudo apt -y update
        sudo apt -y upgrade
        sudo apt -y install asciidoc gettext libncurses5-dev libz-dev lib32gcc1 libc6-dev-i386 flex uglifyjs gcc-multilib msmtp texinfo xmlto qemu-utils upx libelf-dev autopoint device-tree-compiler
      displayName: 'Install dependencies'
    - bash: |
        set -e

        git clone https://github.com/coolsnowwolf/lede.git
        cd lede
        ./scripts/feeds update -a
        ./scripts/feeds install -a

        # update argon theme
        rm -rf package/lean/luci-theme-argon
        git clone -b 18.06 https://github.com/jerrykuku/luci-theme-argon.git package/lean/luci-theme-argon
        
        git clone https://github.com/tty228/luci-app-serverchan.git package/feeds/luci/luci-app-serverchan
        git clone https://github.com/destan19/OpenAppFilter.git package/OpenAppFilter
        ./scripts/feeds update -a
        ./scripts/feeds install -a
        
        cp -rf ../ci/config.seed .config
        make defconfig
      displayName: 'Checkout lede, update feeds'
    - bash: |
        set -e
        
        cd lede
        echo "CPU Cores: "$(nproc)
        make -j$(nproc) || make -j$(nproc) || make -j1 V=s
      displayName: 'Build'
    - bash: |
        cp -rf ./lede/bin/targets/ $(Build.ArtifactStagingDirectory)/
      displayName: 'Copy files to artifacts directory'
    - task: PublishBuildArtifacts@1
      inputs:
        PathtoPublish: '$(Build.ArtifactStagingDirectory)'
        ArtifactName: lede
        publishLocation: Container
      condition: succeededOrFailed()
      displayName: 'Publish artifacts'

  timeoutInMinutes: 300
